### ISSUE TITLE
NOT AN ISSUE (feel free to close)

### ISSUE THREAD

**Issue by apahl** [corsix/polyfill-glibc#4]
Hi, since there is no way on Github to give authors praise for their projects, please excuse me for abusing the issue tracker, since I really wanted to let you know how great and useful this project is.  
I frequently write programs that need to run on an in-house compute cluster with a quite old Centos. So far the only compiled language whose programs would run on the cluster when compiled locally on my Ubuntu Laptop were Go programs (as advertised). For all other languages, I would need to install the development env on the cluster and compile the programs there, which in the case of Rust, would take really long, because of the not-so-great performance of the cluster head node.  
Now, with your project, I was able to transform Rust programs and even AOT-compiled C# programs to run directly on the cluster, after having been compiled on my Laptop. This is a really great life improvement for me.

Thanks a lot for this cool project!

KR Axel

**Comment by corsix** [comment]
I'll close this in the interest of issue tracker cleanliness, but nevertheless it pleases me to hear reports of polyfill-glibc being used.
