### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by Suavesito-Olimpiada** [corsix/polyfill-glibc#5]
Foremost: really nice project! Thanks for it.

I'm building a recipe for `polyfill-glibc` for [`Yggdrasil`](https://github.com/JuliaPackaging/Yggdrasil), the Julia language binary builder recipe book. To be accepted, it needs to have a LICENSE file; which is missing from the current repo structure.

**Comment by corsix** [comment]
I've pushed f2005b7 - is that sufficient for you?

**Comment by Suavesito-Olimpiada** [comment]
Yes. Thank you very much! 😄
