### ISSUE TITLE
Glibc 2.38 fscanf error

### ISSUE THREAD

**Issue by MageSlayer** [corsix/polyfill-glibc#7]
Hi 

I am trying to change required glibc for manually built recent LuaJIT under 2.38.
However all I get is:

```
$ polyfill-glibc --target-glibc=2.36 ./libluajit.so 
Cannot change target version of ./libluajit.so to 2.36 (x86_64) due to missing knowledge about how to handle:
  __isoc23_fscanf@GLIBC_2.38
```

Checked under 918c6813ed9bf867a4f2b162e471d4498eeed428 commit.
Is it something worth reporting?

**Comment by corsix** [comment]
I've opted for the slightly lazy approach in [24167a8](https://github.com/corsix/polyfill-glibc/commit/24167a8d79e8e3e7cbc4941b689023d65d156637) of renaming this function to its C99 equivalent.

**Comment by MageSlayer** [comment]
Thanks!
